/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screen;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author baduy
 */
public class FormMenu extends javax.swing.JFrame {

    public FormMenu() {
        initComponents();

        setIconImage(new ImageIcon("src/main/java/images/icon.png").getImage());
        setTitle("Sudoku");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBottom = new javax.swing.JPanel();
        createPanel = new javax.swing.JPanel();
        createLabel = new javax.swing.JLabel();
        helpPanel = new javax.swing.JPanel();
        helpLabel = new javax.swing.JLabel();
        startPanel = new javax.swing.JPanel();
        startLabel = new javax.swing.JLabel();
        quitPanel = new javax.swing.JPanel();
        quitLabel = new javax.swing.JLabel();
        sudokuLabel = new javax.swing.JLabel();
        playNowLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelBottom.setBackground(new java.awt.Color(245, 245, 245));
        panelBottom.setPreferredSize(new java.awt.Dimension(500, 350));
        panelBottom.setLayout(null);

        createPanel.setBackground(new java.awt.Color(255, 215, 0));
        createPanel.setToolTipText("");
        createPanel.setAutoscrolls(true);
        createPanel.setPreferredSize(new java.awt.Dimension(170, 70));
        createPanel.setVerifyInputWhenFocusTarget(false);

        createLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        createLabel.setForeground(new java.awt.Color(255, 255, 255));
        createLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createLabel.setText("CREATE");
        createLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout createPanelLayout = new javax.swing.GroupLayout(createPanel);
        createPanel.setLayout(createPanelLayout);
        createPanelLayout.setHorizontalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(createLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        createPanelLayout.setVerticalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(createLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelBottom.add(createPanel);
        createPanel.setBounds(270, 170, 150, 50);

        helpPanel.setBackground(new java.awt.Color(0, 255, 127));
        helpPanel.setToolTipText("");
        helpPanel.setAutoscrolls(true);
        helpPanel.setPreferredSize(new java.awt.Dimension(170, 70));
        helpPanel.setVerifyInputWhenFocusTarget(false);

        helpLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        helpLabel.setForeground(new java.awt.Color(255, 255, 255));
        helpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpLabel.setText("HELP");
        helpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                helpLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout helpPanelLayout = new javax.swing.GroupLayout(helpPanel);
        helpPanel.setLayout(helpPanelLayout);
        helpPanelLayout.setHorizontalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, helpPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(helpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        helpPanelLayout.setVerticalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, helpPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(helpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelBottom.add(helpPanel);
        helpPanel.setBounds(80, 260, 150, 50);

        startPanel.setBackground(new java.awt.Color(0, 0, 205));
        startPanel.setToolTipText("");
        startPanel.setAutoscrolls(true);
        startPanel.setPreferredSize(new java.awt.Dimension(170, 70));
        startPanel.setVerifyInputWhenFocusTarget(false);

        startLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        startLabel.setForeground(new java.awt.Color(255, 255, 255));
        startLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startLabel.setText("START");
        startLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                startLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(startLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(startLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelBottom.add(startPanel);
        startPanel.setBounds(80, 170, 150, 50);

        quitPanel.setBackground(new java.awt.Color(255, 48, 48));
        quitPanel.setToolTipText("");
        quitPanel.setAutoscrolls(true);
        quitPanel.setPreferredSize(new java.awt.Dimension(170, 70));
        quitPanel.setVerifyInputWhenFocusTarget(false);

        quitLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        quitLabel.setForeground(new java.awt.Color(255, 255, 255));
        quitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quitLabel.setText("QUIT");
        quitLabel.setToolTipText("");
        quitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quitLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                quitLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout quitPanelLayout = new javax.swing.GroupLayout(quitPanel);
        quitPanel.setLayout(quitPanelLayout);
        quitPanelLayout.setHorizontalGroup(
            quitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quitPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(quitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        quitPanelLayout.setVerticalGroup(
            quitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quitPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(quitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelBottom.add(quitPanel);
        quitPanel.setBounds(270, 260, 150, 50);

        sudokuLabel.setFont(new java.awt.Font("Mistral", 1, 108)); // NOI18N
        sudokuLabel.setForeground(new java.awt.Color(255, 130, 71));
        sudokuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sudokuLabel.setText("SUDOKU");
        sudokuLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelBottom.add(sudokuLabel);
        sudokuLabel.setBounds(0, 10, 500, 120);

        playNowLabel.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        playNowLabel.setForeground(new java.awt.Color(153, 50, 204));
        playNowLabel.setText("play now!");
        playNowLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playNowLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playNowLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                playNowLabelMousePressed(evt);
            }
        });
        panelBottom.add(playNowLabel);
        playNowLabel.setBounds(370, 110, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startLabelMousePressed
        FormSudoku sudokuForm = new FormSudoku();
        sudokuForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_startLabelMousePressed

    private void createLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createLabelMousePressed
        FormCreateSudoku sudokuCreateForm = new FormCreateSudoku();
        sudokuCreateForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createLabelMousePressed

    private void helpLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLabelMousePressed
        JOptionPane.showMessageDialog(this, "1. Sudoku grid consists of 9x9 spaces."
                + "\n2. You can use only numbers from 1 to 9."
                + "\n3. Each 3×3 block can only contain numbers from 1 to 9."
                + "\n4. Each vertical column can only contain numbers from 1 to 9."
                + "\n5. Each horizontal row can only contain numbers from 1 to 9."
                + "\n6. Each number in the 3×3 block, vertical column or horizontal row can be used only once."
                + "\n7. The game is over when the whole Sudoku grid is correctly filled with numbers.", "SUDOKU'S BASIC RULES",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_helpLabelMousePressed


    private void quitLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitLabelMousePressed
        System.exit(0);
    }//GEN-LAST:event_quitLabelMousePressed

    private void playNowLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playNowLabelMousePressed
        JOptionPane.showMessageDialog(this, "Sudoku, a DSA project by Nguyen Ba Duy - ITDSIU21014", "INFO", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_playNowLabelMousePressed

    private void startLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startLabelMouseEntered
        startPanel.setBackground(new Color(65, 105, 225));
    }//GEN-LAST:event_startLabelMouseEntered

    private void startLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startLabelMouseExited
        startPanel.setBackground(new Color(0, 0, 205));
    }//GEN-LAST:event_startLabelMouseExited

    private void createLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createLabelMouseEntered
        createPanel.setBackground(new Color(255, 236, 139));
    }//GEN-LAST:event_createLabelMouseEntered

    private void createLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createLabelMouseExited
        createPanel.setBackground(new Color(255, 215, 0));
    }//GEN-LAST:event_createLabelMouseExited

    private void helpLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLabelMouseEntered
        helpPanel.setBackground(new Color(84, 255, 159));
    }//GEN-LAST:event_helpLabelMouseEntered

    private void helpLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLabelMouseExited
        helpPanel.setBackground(new Color(0, 255, 127));
    }//GEN-LAST:event_helpLabelMouseExited

    private void quitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitLabelMouseEntered
        quitPanel.setBackground(new Color(255, 106, 106));
    }//GEN-LAST:event_quitLabelMouseEntered

    private void quitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitLabelMouseExited
        quitPanel.setBackground(new Color(255, 48, 48));
    }//GEN-LAST:event_quitLabelMouseExited

    private void playNowLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playNowLabelMouseEntered
        playNowLabel.setForeground(new Color(255, 187, 255));
    }//GEN-LAST:event_playNowLabelMouseEntered

    private void playNowLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playNowLabelMouseExited
        playNowLabel.setForeground(new Color(153, 50, 204));
    }//GEN-LAST:event_playNowLabelMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createLabel;
    private javax.swing.JPanel createPanel;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JLabel playNowLabel;
    private javax.swing.JLabel quitLabel;
    private javax.swing.JPanel quitPanel;
    private javax.swing.JLabel startLabel;
    private javax.swing.JPanel startPanel;
    private javax.swing.JLabel sudokuLabel;
    // End of variables declaration//GEN-END:variables
}
