/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screen;

import display.TableSudoku;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author baduy
 */
public class FormLevels extends javax.swing.JFrame {

    private final TableSudoku tableSudoku;

    public FormLevels(TableSudoku tableSudoku) {
        initComponents();
        this.tableSudoku = tableSudoku;

        panelBottom.setBorder(BorderFactory.createLineBorder(Color.BLACK, 3));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBottom = new javax.swing.JPanel();
        hardPanel = new javax.swing.JPanel();
        hardLabel = new javax.swing.JLabel();
        mediumPanel = new javax.swing.JPanel();
        mediumLabel = new javax.swing.JLabel();
        easyPanel = new javax.swing.JPanel();
        easyLabel = new javax.swing.JLabel();
        nightmarePanel = new javax.swing.JPanel();
        nightmareLabel = new javax.swing.JLabel();
        sudokuLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));

        panelBottom.setBackground(new java.awt.Color(245, 245, 245));
        panelBottom.setPreferredSize(new java.awt.Dimension(300, 400));
        panelBottom.setLayout(null);

        hardPanel.setBackground(new java.awt.Color(255, 48, 48));
        hardPanel.setToolTipText("");
        hardPanel.setAutoscrolls(true);
        hardPanel.setPreferredSize(new java.awt.Dimension(170, 70));
        hardPanel.setVerifyInputWhenFocusTarget(false);

        hardLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        hardLabel.setForeground(new java.awt.Color(255, 255, 255));
        hardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hardLabel.setText("HARD");
        hardLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hardLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hardLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hardLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hardLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout hardPanelLayout = new javax.swing.GroupLayout(hardPanel);
        hardPanel.setLayout(hardPanelLayout);
        hardPanelLayout.setHorizontalGroup(
            hardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hardPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hardPanelLayout.setVerticalGroup(
            hardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hardPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelBottom.add(hardPanel);
        hardPanel.setBounds(70, 250, 150, 50);

        mediumPanel.setBackground(new java.awt.Color(100, 149, 237));
        mediumPanel.setToolTipText("");
        mediumPanel.setAutoscrolls(true);
        mediumPanel.setPreferredSize(new java.awt.Dimension(170, 70));
        mediumPanel.setVerifyInputWhenFocusTarget(false);

        mediumLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        mediumLabel.setForeground(new java.awt.Color(51, 51, 51));
        mediumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mediumLabel.setText("MEDIUM");
        mediumLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mediumLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mediumLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mediumLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mediumLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout mediumPanelLayout = new javax.swing.GroupLayout(mediumPanel);
        mediumPanel.setLayout(mediumPanelLayout);
        mediumPanelLayout.setHorizontalGroup(
            mediumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mediumPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mediumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mediumPanelLayout.setVerticalGroup(
            mediumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mediumPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mediumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelBottom.add(mediumPanel);
        mediumPanel.setBounds(70, 180, 150, 50);

        easyPanel.setBackground(new java.awt.Color(100, 149, 237));
        easyPanel.setToolTipText("");
        easyPanel.setAutoscrolls(true);
        easyPanel.setPreferredSize(new java.awt.Dimension(170, 70));
        easyPanel.setVerifyInputWhenFocusTarget(false);

        easyLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        easyLabel.setForeground(new java.awt.Color(255, 255, 255));
        easyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        easyLabel.setText("EASY");
        easyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                easyLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                easyLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                easyLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout easyPanelLayout = new javax.swing.GroupLayout(easyPanel);
        easyPanel.setLayout(easyPanelLayout);
        easyPanelLayout.setHorizontalGroup(
            easyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, easyPanelLayout.createSequentialGroup()
                .addComponent(easyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        easyPanelLayout.setVerticalGroup(
            easyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(easyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panelBottom.add(easyPanel);
        easyPanel.setBounds(70, 110, 150, 50);

        nightmarePanel.setBackground(new java.awt.Color(255, 48, 48));
        nightmarePanel.setToolTipText("");
        nightmarePanel.setAutoscrolls(true);
        nightmarePanel.setPreferredSize(new java.awt.Dimension(170, 70));
        nightmarePanel.setVerifyInputWhenFocusTarget(false);

        nightmareLabel.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        nightmareLabel.setForeground(new java.awt.Color(0, 0, 0));
        nightmareLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nightmareLabel.setText("NIGHTMARE");
        nightmareLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nightmareLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nightmareLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nightmareLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nightmareLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout nightmarePanelLayout = new javax.swing.GroupLayout(nightmarePanel);
        nightmarePanel.setLayout(nightmarePanelLayout);
        nightmarePanelLayout.setHorizontalGroup(
            nightmarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nightmarePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nightmareLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        nightmarePanelLayout.setVerticalGroup(
            nightmarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nightmarePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nightmareLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelBottom.add(nightmarePanel);
        nightmarePanel.setBounds(70, 320, 150, 50);

        sudokuLabel.setFont(new java.awt.Font("Mistral", 1, 84)); // NOI18N
        sudokuLabel.setForeground(new java.awt.Color(255, 130, 71));
        sudokuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sudokuLabel.setText("SUDOKU");
        panelBottom.add(sudokuLabel);
        sudokuLabel.setBounds(0, 10, 300, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void mediumLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mediumLabelMousePressed
        tableSudoku.generateSudoku(2);
        this.setVisible(false);
    }//GEN-LAST:event_mediumLabelMousePressed

    private void hardLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardLabelMousePressed
        tableSudoku.generateSudoku(3);
        this.setVisible(false);
    }//GEN-LAST:event_hardLabelMousePressed

    private void nightmareLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nightmareLabelMousePressed
        tableSudoku.generateSudoku(4);
        this.setVisible(false);
    }//GEN-LAST:event_nightmareLabelMousePressed

    private void easyLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyLabelMousePressed
        tableSudoku.generateSudoku(1);
        this.setVisible(false);
    }//GEN-LAST:event_easyLabelMousePressed

    private void easyLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyLabelMouseEntered
        easyPanel.setBackground(new Color(135, 206, 235));
    }//GEN-LAST:event_easyLabelMouseEntered

    private void easyLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyLabelMouseExited
        easyPanel.setBackground(new Color(100, 149, 237));
    }//GEN-LAST:event_easyLabelMouseExited

    private void mediumLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mediumLabelMouseEntered
        mediumPanel.setBackground(new Color(135, 206, 235));
    }//GEN-LAST:event_mediumLabelMouseEntered

    private void mediumLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mediumLabelMouseExited
        mediumPanel.setBackground(new Color(100, 149, 237));
    }//GEN-LAST:event_mediumLabelMouseExited

    private void hardLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardLabelMouseEntered
        hardPanel.setBackground(new Color(255, 106, 106));
    }//GEN-LAST:event_hardLabelMouseEntered

    private void hardLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardLabelMouseExited
        hardPanel.setBackground(new Color(255, 48, 48));
    }//GEN-LAST:event_hardLabelMouseExited

    private void nightmareLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nightmareLabelMouseEntered
        nightmarePanel.setBackground(new Color(255, 106, 106));
    }//GEN-LAST:event_nightmareLabelMouseEntered

    private void nightmareLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nightmareLabelMouseExited
        nightmarePanel.setBackground(new Color(255, 48, 48));
    }//GEN-LAST:event_nightmareLabelMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel easyLabel;
    private javax.swing.JPanel easyPanel;
    private javax.swing.JLabel hardLabel;
    private javax.swing.JPanel hardPanel;
    private javax.swing.JLabel mediumLabel;
    private javax.swing.JPanel mediumPanel;
    private javax.swing.JLabel nightmareLabel;
    private javax.swing.JPanel nightmarePanel;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JLabel sudokuLabel;
    // End of variables declaration//GEN-END:variables
}
